plugins:
  discourse_antivirus_enabled:
    default: false
    validator: DiscourseAntivirus::EnableDiscourseAntivirusValidator
  antivirus_live_scan_images:
    default: false
  antivirus_srv_record:
    default: ''
  flag_malicious_uploads:
    default: false
