plugins:
  discourse_antivirus_enabled:
    default: false
  antivirus_live_scan_images:
    default: false
  antivirus_clamav_hostname:
    default: localhost
  antivirus_clamav_port:
    default: 3310
